// Code generated by tabuyos. DO NOT EDIT!

// Package dto
// @author tabuyos
// @since 2023/08/01
// @description account
package dto

import (
	"github.com/jinzhu/copier"
	"metis/test/second/model/entity"
)

type Account entity.Account

func NewAccount() *Account {
	return &Account{}
}
func (rec *Account) From(from *entity.Account) error {
	err := copier.Copy(rec, from)
	return err
}
func (rec *Account) Into(into *entity.Account) error {
	err := copier.Copy(into, rec)
	return err
}
