// Code generated by tabuyos. DO NOT EDIT!

// Package dto
// @author tabuyos
// @since 2023/07/31
// @description survey
package dto

import "metis/test/second/model/entity"

type Survey entity.Survey
