[mysql.base]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[mysql.single]
addr = "127.0.0.1:3307"
name = "metis"
pass = "root"
user = "root"

[mysql.read]
addr = "127.0.0.1:3306"
name = "metis-read"
pass = "root"
user = "root"

[mysql.write]
addr = "127.0.0.1:3306"
name = "metis-wirte"
pass = "root"
user = "root"
