// Code generated by tabuyos. DO NOT EDIT!

// Package entity
// @author tabuyos
// @since 2023/07/31
// @description survey
package entity

import (
	"github.com/jinzhu/copier"
	"time"
)

type Survey struct {
	*IDInfo
	Title       *string
	Description *string
	StartAt     *time.Time
	EndAt       *time.Time
	Status      *int8
	Top         *int8
	CreatorBy   *int64
	UpdaterBy   *int64
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

func NewSurvey() *Survey {
	return &Survey{}
}
func (rec *Survey) From(from any) error {
	err := copier.Copy(rec, from)
	return err
}
func (rec *Survey) Into(into *any) error {
	err := copier.Copy(into, rec)
	return err
}
