// Code generated by tabuyos. DO NOT EDIT!

// Package entity
// @author tabuyos
// @since 2023/07/30
// @description survey
package entity

import (
	"github.com/jinzhu/copier"
	"time"
)

type Survey struct {
	*IDInfo
	Title   *string
	StartAt *time.Time
}

func NewSurvey() *Survey {
	return &Survey{}
}
func (rec *Survey) From(from any) error {
	err := copier.Copy(rec, from)
	return err
}
func (rec *Survey) Into(into *any) error {
	err := copier.Copy(into, rec)
	return err
}
