// Code generated by log-gen. DO NOT EDIT.
package entity // hellllllo
import "time"

type Survey struct {
	ID      int64     `json:"id"`
	Title   string    `json:"title"`
	StartAt time.Time `json:"startAt"`
}

func (rec *Survey) Doi(a *string, b *int) (s, x string) {
	return "id", "id"
}
